### ISSUE TITLE
Add regex extractor

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#182]
Add extractor to use Python regex to extract data. Designed to use the full capabilities of the Python `re` package.

The template for the extractor is in https://github.com/szeke/etk/blob/182-regex/etk/extractors/regex_extractor.py (new branch 182-regex

**Comment by szeke** [comment]
Please add FINDALL and SPLIT to match modes, to invoke the corresponding functions in the re package @linqyd

**Comment by szeke** [comment]
Also, please make FINDALL be the default, as it is most likely what users want.

**Comment by linqyd** [comment]
finished
