### ISSUE TITLE
Add extractor to extract URLs from text

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#185]
Th URLExtractor identifies well formed URLs such as
`http://isi.edu/abx` and also URLs that don't have `http`, such as `dig.isi.edu/index.html`

The URLs without http should be converted to start with http so that they can be dereferenced.

An argument for the extractor specifies whether to try to identify URLs that don't have http.

`allow_missing_http` and the default should be false.

**Comment by Lituta** [comment]
finished in Pull Request #193
