### ISSUE TITLE
Refactor html_metadata_extractor.py

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#194]
Instead of returning a dict with `{ "meta": { "author": "...", ...}, "title": ...}`

lets return an Extraction for each category, and use the `tag` attribute of extractions to specify what is being returned. For example, the title extraction will have tag `title`, the meta extraction has tag `meta`, etc.

**Comment by linqyd** [comment]
the value of each extraction could be any type or must be dict?
e.g. for title extraction: 
1. must be extraction.value = `{"title": "title_text"}` 
or 
2. could be extraction.value = `"title_text"`

The second one is my current implementation.

**Comment by szeke** [comment]
That is correct.

**Comment by linqyd** [comment]
finished
