### ISSUE TITLE
content and metadata extraction need to get their input as an argument

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#195]
In `examples/html_basic/html_basic_extraction.py`
we are invoking as `doc.invoke_extractor(content_extractor, strategy=Strategy.ALL_TEXT)`.

It should be 
```
raw = doc.select_segments("$.raw_content")[0]
doc.invoke_extractor(content_extractor, raw, strategy=Strategy.ALL_TEXT)
```

**Comment by Lituta** [comment]
finished in Pull Request #193
