### ISSUE TITLE
revise date_extractor

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#200]
The date_extractor in etk2 is using a collection of regex to parse dates, and my suspicion is that the recall is not good.

Instead of using regex we should use SpaCy. We should implement two versions:

1) Port the old SpaCy date extractor in https://github.com/usc-isi-i2/etk/blob/master/etk/spacy_extractors/date_extractor.py

2) Use the default Spacy NER to extract dates, and use parse_date to verify that they are dates

**Comment by RqS** [comment]
I stuck on some problems implementing general spacy rule extractor with operators about multiple matches. We should discuss the problems on Tuesday. I can move to work on this first.

**Comment by szeke** [comment]
```
def extract(self, text: str=None, 
    extract_first_date_only: bool=False, # useful for news stories where the first date is typically the publication date.
    date_formats: List(str)=[], # when specified, only extract the given formats.
    ignore_dates_before: datetime.datetime=None, 
    ignore_dates_after: datetime.datetime=None,
    detect_relative_dates: bool=True,
    relative_base: datetime.datetime=None,
    preferred_date_order: str="MDY", # used for interpreting ambiguous dates that are missing parts
    prefer_language_date_order: bool=True,
    timezone: str=None, # default is local timezone.
    to_timezone: str=None, # when not specified, not timezone conversion is done.
    return_as_timezone_aware: bool=True, # when false don't do timezime conversions.
    prefer_day_of_month: str="first", # can be "current", "first", "last".
    prefer_dates_from: str="current" # can be "current", "first", "last".
                ) -> List[Extraction]:

def parse_date(self, str_date: str, 
    # same params as extract, except for extract_first_date_only
) -> datetime.datetime or None:

class DateResolution(Enum):
    """

    """
    SECOND = auto()
    MINUTE = auto()
    DAY = auto()
    MONTH = auto()
    YEAR = auto()

def convert_to_iso_format(date: datetime.datetime, resolution: DateResolution=DateResolution.DAY)
    """"""
```

Challenges

- SpaCy cannot extract many date formats that we want.
- SpaCy often extracts day or week as separate date: eg. saturday, 1 february 2014 is extracted as two DATE extractions.
- parse_date cannot parse all the dates that SpaCy can extract.


To build a robust date extractor we need to employ multiple strategies:

1. Many regexes that we custom build to identify many of the common date/time formats that we want to extract.
2. Use SpaCy DATE and TIME entity recognition
3. Use strategies to remove SpaCy false positives.
   1. when day of week extraction immediately preceds a DATE extraction, ignore the day of week
   2. when TIME extraction immediately follows DATE extraction, ignore the TIME extraction

**Comment by szeke** [comment]
@linqyd please work on this issue, we will use SpaCy NER, so we don't need theSpaCy rules.

**Comment by szeke** [comment]
Use the ground truth in #202 to develop this extractor

**Comment by szeke** [comment]
After the discussion today, let's not use Spacy NER. We can use Spacy rules for the relative dates, and extract the absolute dates with regex

**Comment by Lituta** [comment]
done with pull request #213
