### ISSUE TITLE
create comprehensive ground truth for date extractor

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#202]
We need a really robust date extractor, so we need to create a comprehensive ground truth and use it to implement unit tests.

We should have three sets of ground truths:

1) Absolute dates in English in a wide variety of formats

2) Relative dates

3) Dates in other languages such as Spanish and French

**Comment by szeke** [comment]
I started a ground truth with examples that we had to parse in the past: 
https://github.com/szeke/etk/blob/etk2/examples/dates/date_ground_truth.txt

Needs to be completed before it can be used for comprehensive testing.

**Comment by Lituta** [comment]
done with pull request #233
