### ISSUE TITLE
[etk2] Extraction Module

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/etk#214]
![wechatimg41](https://user-images.githubusercontent.com/6547905/38180253-0494e5a4-35e0-11e8-8a2b-8d8067be82c4.jpeg)

**Comment by RqS** [comment]
Topological order is not implemented yet

**Comment by szeke** [comment]
Please rename `ExtractionModule` to `ETKModule`

**Comment by saggu** [comment]
Obsolete, closing
