### ISSUE TITLE
store_extractions should be available in Document too

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#222]
https://github.com/usc-isi-i2/etk/blob/36ef75c1983ab4b1ea1549d5ea2be50482ca08fc/etk/segment.py#L37

The idea is that people can do `doc.store_extractions` rather than having to do:
```
root = doc.select_segments("$")[0]
root.store_extractions(...)
```

We could do this with a new abstract class `Storeable` similar to `Extractable` so that `Segment` and `Document` are subclasses of `Storable`

Update examples so there is no need to define a `root` to store extractions at the root of a document.

**Comment by RqS** [comment]
Implemented by making Document the subclass of Segment
