### ISSUE TITLE
Create html_link extractor

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#226]
To extract links in `a`, `img`, `video` and whatever else in HTML has link. Should extract the `href`, alternate text and whatever other common attributes are associated with these tags.

Should be similar to https://github.com/usc-isi-i2/etk/blob/master/etk/data_extractors/link_extractor.py, but the result should be a plain dict of all the elements extracted (instead of value/metadata used in the old extractor)

**Comment by saggu** [comment]
Obsolete, closing
