### ISSUE TITLE
Identify similar news stories given a sentence

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#240]
This task is useful in SAGE, and provides an illustration of how to use spaCy in ETK. We will do this in several steps.

The test set consists of one sentence: `Will Kim Jong-un meet the head of government from any G7 nation in-person before 1 June 2018?`, and 100,000 news stories from Lexis Nexis.

- [x] Run experiment to find the K closest articles to the story using the spaCy similarity function to compare the sentence to the news story title.
- [x] Run experiment to find the K closest articles comparing the given sentence to each sentence in the article and using as `score(sentence, article) = max score(sentence, s)` for each sentence s in article.

We will evaluate the results and run additional experiments if additional tuning is necessary.

If the results are good, we will implement and `ETKModule` that is given as input a set of pairs `(ifp_id, ifp_title)`. The process method will get as input a news story `Document`. Using spaCy, compare the `ifp_title` to the `Document` and if the similarity is above a threshold, TBD, create a new Document with the following knowledge graph:

```
{
  'type': 'News/IFP Relevance',
  'date': 'the posting date of the news story',
  'ifp': 'the given ifp_id',
  'news_story': 'doc-id of the news story',
  'similarity': 'similarity score as computed by the best algorithm above'
}
```

In the SAGE gui it will be possible to retrieve the doc-ids of the closest stories given an IFP and a day.

**Comment by saggu** [comment]
Closing
