### ISSUE TITLE
Clean up names of functions and files

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#241]
Do the following renamings:

- [x] `invoke_extractor` becomes `extract`
- [x] `store_extraction` becomes `store`
- [x] file `etk_extraction.py` becomes `extraction.py` (to be consistent with the other file names)
- [x] file `etk_field_types.py` becomes `field_type.py`
- [x] file `extraction_module.py` becomes `etk_module.py` (class `ExtractionModule` becomes `ETKModule`)

**Comment by RqS** [comment]
Done
