### ISSUE TITLE
CsvProcessor parses dates as Python objects, so JSON does not serialize

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#266]
The CsvProcessor converts dates in Excel sheets to Python dates, and the JSON does not serialize. Looks like the code calls pyexcel with date parsing turned off, but the output still contains Python dates. The following file illustrates the problem:
[ucdp_sample.xls.zip](https://github.com/usc-isi-i2/etk/files/1984399/ucdp_sample.xls.zip)

If this is a bug in pyexcel, we need to scan the output and replace the date objects with strings, we could do that by converting them to ISO format.

**Comment by linqyd** [comment]
Yes, I double checked the document, it seems that the argument 'auto_detect_datetime' doesn't work for excel file. Let me know if the ISO format datetime string isn't in desired format.

**Comment by szeke** [comment]
Thanks @linqyd I accepted the change.
