### ISSUE TITLE
[etk2] etk.py terminates throwing FileNotFoundError for the logger

### ISSUE THREAD

**Issue by iAmeeth** [usc-isi-i2/etk#268]
The script fails on windows machine since the hardcoded path "/tmp/etk.log" does not exist.

`FileNotFoundError: [Errno 2] No such file or directory: 'Y:\\tmp\\etk.log'
`

**Comment by szeke** [comment]
@iAmeeth can you please fork and implement a fix, then do a pull request.

**Comment by saggu** [comment]
Obsolete, closing
