### ISSUE TITLE
date extractor too slow, even when providing additional_formats

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#279]
For example, using
```
doc.extract(self.date_extractor, s,
    prefer_language_date_order=None,
    additional_formats=["%Y%m%d"],
    use_default_formats=False)
```
should be fast as it shouldn't use the default formats.

**Comment by Lituta** [comment]
It might be because of the relative date extraction using spacy rules. Set "detect_relative_dates" to be "False" should speed up the extraction.

**Comment by szeke** [comment]
Yes, `detect_relative_dates=False` speeds it up considerably. I made it the default.
