### ISSUE TITLE
unit test for ExcelExtractor

### ISSUE THREAD

**Issue by linqyd** [usc-isi-i2/etk#335]
The unit test for ExcelExtractor doesn't test the API ExcelExtractor.extract(), instead, it tests the auxiliary methods col_name_to_num(), row_name_to_num(), parse_variable(), which should be private.

I've changed all method of ExcelExtractor except ExcelExtractor.extract() to private, which raises three test cases of ExcelExtractor fail. Please modify the unit test for ExcelExtractor.

**Comment by GreatYYX** [comment]
You can update test cases.
