### ISSUE TITLE
date_extractor test case fails 

### ISSUE THREAD

**Issue by linqyd** [usc-isi-i2/etk#339]

**Comment by linqyd** [comment]
**The failed test case sits in the unit_test/ground_truth/date_ground_truth.txt line 34: Sat, Mar 10|2018-03-10|%a, %b %d**

Below is the error message.

FAIL: test_ground_truth (etk.unit_tests.test_date_extractor.TestDateExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Sylvia/etk/etk/unit_tests/test_date_extractor.py", line 80, in test_ground_truth
    self.assertEqual(e[0].value if e else '', expected)
AssertionError: '2019-03-10' != '2018-03-10'
- 2019-03-10
?    ^
+ 2018-03-10
?    ^

**Comment by GreatYYX** [comment]
@Lituta pls take a look
