### ISSUE TITLE
Date extractor not working as expected!

### ISSUE THREAD

**Issue by sobalgi** [usc-isi-i2/etk#373]
I was trying out date extraction as a part of [#265 comment of DIG](https://github.com/usc-isi-i2/dig-etl-engine/issues/265#issuecomment-423595430).
![image](https://user-images.githubusercontent.com/36876424/46574783-911b6780-c9c6-11e8-8ab6-d7cbb858c813.png)

The relative date extraction seems to be not working is date extractor. screenshot below.
![image](https://user-images.githubusercontent.com/36876424/46574827-50701e00-c9c7-11e8-96e9-c8167250e807.png)

The ```9 days before``` example from [ETK documention](https://usc-isi-i2.github.io/etk/extractors/date_ext.html) is not getting extracted. The other 2 dates are getting extracted fine.

Can you you please point me in the right direction of any additional documentation, if any ?

**Comment by Lituta** [comment]
Hi to enable the relative date extraction you need to pass in a ETK instance when init the DateExtractor:
```
from etk.etk import ETK
from etk.extractors.date_extractor import DateExtractor
import datetime
de = DateExtractor(ETK())
de.extract(text='9 days before i.e 28-09-2018 27 Sep, 2018', detect_relative_dates=True, relative_base=datetime.datetime.today(), preferred_date_order='DMY')
```
Sorry about that we will update in the documentation

**Comment by sobalgi** [comment]
Hello,
Thanks for the right instructions. Everything seems to be working fine now!?

I'm having some peculiar issue with the sample date inputs. This might be too trivial but these are some of the basic examples. Please find the samples below.

```
from etk.etk import ETK
from etk.extractors.date_extractor import DateExtractor
import datetime
de = DateExtractor(ETK())
dates = de.extract(text='2 days before i.e 07-10-2018 or \
                   08 Oct, 2018 or Oct 8th, 2018 or \
                   October 9th, 2018 or Tuesday or \
                   October 10th, 2018 or wednesday or \
                   Yesterday or Day before yesterday or \
                   Dec or 10th Dec or \
                   he may go to his hometown tomorrow or \
                   13X or today or Today',
                   detect_relative_dates=True, 
                   relative_base=datetime.datetime.today(), # today = 09-Oct-2018
                   preferred_date_order='DMY',
                   prefer_day_of_month='first',
                   prefer_dates_from='current')

for i,date in enumerate(dates):
    print(f'{i+1}) {date.value} : {date.original_date}')
```
Here the output is 
```
1) 2018-10-07 : 07-10-2018
2) 2018-10-08 : 08 Oct, 2018
3) 2018-10-08 : Oct 8th, 2018
4) 2018-10-09 : October 9th, 2018
5) 2018-10-09 : Tuesday
6) 2018-10-10 : October 10th, 2018
7) 2018-10-10 : wednesday
8) 2018-12-01 : Dec
9) 2018-12-10 : 10th Dec
10) 2018-05-01 : may
11) 2019-03-01 : 13X
12) 2018-10-07 : 2 days before
13) 2018-10-08 : Yesterday
14) 2018-10-07 : Day before yesterday
15) 2018-10-10 : tomorrow
```
The more difficult patterns like ```wednesday, Yesterday, Day before yesterday or 2 days before``` all seems to be extracted fine. But the simple ```may``` in ```he may go to his hometown tomorrow``` or ```today, Today``` doesnot work ?! 

Also ```13X``` which is some garbage seems to be extracted somehow!!

If you observe carefully, the **preferred_date_order='DMY'** seems to fail when it encounters a dubious dates. 

Can you please confirm these behaviors ?

I would like to know if these can be somehow overcome.

Many thanks,
@sobalgi

**Comment by sobalgi** [comment]
Hello @Lituta,

Few more false positive and false negative examples !!!

```
from etk.etk import ETK
from etk.extractors.date_extractor import DateExtractor
import datetime
de = DateExtractor(ETK())
dates = de.extract(text='3D or 3J or 3L or 3M or 3S or 3V or 3X or Mars \
                    today or Today', # False positives and False Negative examples respectively
                   detect_relative_dates=True, 
                   relative_base=datetime.datetime.today(), # today = 09-Oct-2018
                   preferred_date_order='DMY',
                   prefer_day_of_month='first',
                   prefer_dates_from='current')

for i,date in enumerate(dates):
    print(f'{i+1}) {date.value} : {date.original_date}\t {date.confidence}')
```

These samples ```3D or 3J or 3L or 3M or 3S or 3V or 3X or Mars``` which should not have been extracted are being extracted somehow.

However ```today or Today``` which should have been extracted is not getting extracted at all.

Also may I know what the confidence in date extraction object indicate

**Comment by Lituta** [comment]
see #374
