### ISSUE TITLE
Strange behavior of date extractor.

### ISSUE THREAD

**Issue by sobalgi** [usc-isi-i2/etk#374]
Thanks for the right instructions. Everything seems to be working fine now!?

I'm having some peculiar issue with the sample date inputs. This might be too trivial but these are some of the basic examples. Please find the samples below.

```
from etk.etk import ETK
from etk.extractors.date_extractor import DateExtractor
import datetime
de = DateExtractor(ETK())
dates = de.extract(text='2 days before i.e 07-10-2018 or \
                   08 Oct, 2018 or Oct 8th, 2018 or \
                   October 9th, 2018 or Tuesday or \
                   October 10th, 2018 or wednesday or \
                   Yesterday or Day before yesterday or \
                   Dec or 10th Dec or \
                   he may go to his hometown tomorrow or \
                   13X or today or Today',
                   detect_relative_dates=True, 
                   relative_base=datetime.datetime.today(), # today = 09-Oct-2018
                   preferred_date_order='DMY',
                   prefer_day_of_month='first',
                   prefer_dates_from='current')

for i,date in enumerate(dates):
    print(f'{i+1}) {date.value} : {date.original_date}')
```
Here the output is 
```
1) 2018-10-07 : 07-10-2018
2) 2018-10-08 : 08 Oct, 2018
3) 2018-10-08 : Oct 8th, 2018
4) 2018-10-09 : October 9th, 2018
5) 2018-10-09 : Tuesday
6) 2018-10-10 : October 10th, 2018
7) 2018-10-10 : wednesday
8) 2018-12-01 : Dec
9) 2018-12-10 : 10th Dec
10) 2018-05-01 : may
11) 2019-03-01 : 13X
12) 2018-10-07 : 2 days before
13) 2018-10-08 : Yesterday
14) 2018-10-07 : Day before yesterday
15) 2018-10-10 : tomorrow
```
The more difficult patterns like ```wednesday, Yesterday, Day before yesterday or 2 days before``` all seems to be extracted fine. But the simple ```may``` in ```he may go to his hometown tomorrow``` or ```today, Today``` doesnot work ?! 

Also ```13X``` which is some garbage seems to be extracted somehow!!

If you observe carefully, the **preferred_date_order='DMY'** seems to fail when it encounters a dubious dates. 

Can you please confirm these behaviors ?

I would like to know if these can be somehow overcome.

Many thanks,
@sobalgi

_Originally posted by @sobalgi in https://github.com/usc-isi-i2/etk/issues/373#issuecomment-428071238_

**Comment by Lituta** [comment]
fixed in #377
