### ISSUE TITLE
Serialization Issue in ETK

### ISSUE THREAD

**Issue by rijulvohra** [usc-isi-i2/etk#425]
The serialize command in RDFLib has been updated to return a string by default instead of bytes. RDFLib/rdflib#1183 
https://github.com/usc-isi-i2/etk/blob/93fe0592b4f994494ec0f78dcbc5a8a3a21a75cb/etk/knowledge_graph/graph.py#L50
By default ETK serialize command is expecting the serialize command to return bytes.

This is causing an error while using the `kgtk generate_wikidata_triples` command. 

**Steps to reproduce the error**
This error happens if I build rdfLib from master branch.
1. `pip uninstall rdflib`
2. `pip install git+https://github.com/RDFLib/rdflib.git@master`
3. Use `kgtk generate_wikidata_triples` command on a kgtk edge file

**Comment by saggu** [comment]
Fixed in 2.2.5
